spring.application.name=GoDo

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.public-key=classpath:keys/key.pub
jwt.private-key=classpath:keys/private.key
jwt.ttl=${JWT_TTL}
application.security.jwt.refresh-token-ttl=${RT_TTL}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

app.host.url=${HOST_URL}