server {
    listen 80;
    location / {
        # when ever a users looks for a file, look for the file in this dir
        # it must match the folder we copied the bundles, stylesheets and pages in
        root /usr/nginx/html;

        # defines the default file
        index index.html index.htm;

        # enables routing for SPA's, first looks for a file with the given name, then for a directory, and if nothing
        # was found goes to index.html, and tries finding the component with that name, if that isn't found as well
        # crash with 404
        try_files $uri $uri/ /index.html =404;
    }
}